<div class="post excerpt ">
	<h2>About figura4</h2>
	<p>
		Questo sito &egrave; la mia "piattaforma didattica", che uso per gli esprimenti in ambito web development.
		Il che significa che questo sito ne ha viste un po' di tutti i colori nel corso degli anni:
		html statico, php, drupal, wordpress, ruby on rails, zend framework sono solo alcune tra le varie incarnazioni.
	</p>
	<p>
		E per unire l'utile al dilettevole, ho scelto di parlare delle mie prinicpali passioni: libri, film e serie tv.<br>
	</p>

	<h2>Contattami</h2>
	<?php echo $this->form ?>
</div>