<div class="post excerpt ">
	<div class="widget">
	<h2>Links</h2>
	<p>
		Raccolta di siti che visito frequentemente.
		Vuoi essere linkato? <a href="/about">Contattami!</a>
	</p>
	<ul>
		<li>
			<p>
				<a href="http://www.bitgrabbers.com">Bitgrabbers</a><br>
				Sito che raccoglie tutti gli screenshot dei videogiochi con cui mi diletto.
			</p>
		</li>
		<li>
			<p>
				<a href="http://fed-tobearockandnottoroll.blogspot.it/">To be a rock and not to roll</a><br>
				Blog di Fed Zeppelin, vichinga d'abruzzo e Whovian D.O.C.
			</p>
		</li>
	</ul>
	</div>
</div>