<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/it_IT/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

<div class="post excerpt ">
	<div class="post-content hreview">
    	<header>
        	<h1 class="title"><?php echo $this->content->getTitle(); ?></h1>
    		<?php echo $this->partial('partials/post-info.phtml', array('content' => $this->content)); ?>
    	</header>
    
    	<?php echo $this->partial('partials/review-box.phtml', array('content' => $this->content, 'author' => $this->content->getAuthor())); ?>
    
    	<div class="description">
    		<h3>Recensione</h3>
    		<?php echo $this->content->body; ?>
    	</div>
    
		<?php echo $this->partial('partials/quotes.phtml', array('content' => $this->content)); ?>
	
		<?php echo $this->partial('partials/author.phtml', array('author' => $this->author)); ?>
    	
    	<div class="fb-like" data-href="<?php echo 'http://' . $_SERVER['SERVER_NAME'] . Zend_Controller_Front::getInstance()->getRequest()->getRequestUri(); ?>" data-send="true" data-width="450" data-show-faces="true"></div>
    	<div>
    		<a href="https://twitter.com/share" class="twitter-share-button" data-via="figura_4" data-lang="it">Tweet</a>
			<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    	</div>
    	
		<?php echo $this->partial('partials/comments.phtml', array('content' => $this->content, 'form' => $this->form)); ?>
	</div>
</div>