<div class="post excerpt ">
<h2>Amministrazione commenti</h2>

<?php echo $this->form;?>

<p>
<?php 
	echo '<a href="' . $this->url(array('controller' => 'comment', 'action' => 'create'), 'default', true) . '" title="create">New</a>';
?>
</p>

<table width="935" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <th scope="col" width="70"></th>
        <th scope="col" width="50">Autore</th>
        <th scope="col" width="170">Data</th>
    </tr>
    <?php 
    	echo $this->partialLoop('tableRows/commentAdmin.phtml', $this->paginator);
    ?>
</table>

<?php echo $this->paginationControl($this->paginator,
                                            'Sliding',
                                            'partials/pagination-control.phtml'); ?>

</div>