<footer>
	<div class="container">
		<div class="footer-widgets">
			<div class="f-widget">
				<div class="widget"><h3>Credits</h3>			
					<div class="textwidget">
						Idea, programmazione (PHP Zend Framework), progettazione database (Mysql), recensioni: Oscar Riva
					</div>
				</div>	
			</div>
			<div class="f-widget">
				<div class="widget"><h3>Disclaimer</h3>			
					<div class="textwidget">
						Questo sito non ha scopo di lucro. Ogni immagine, logo o citazione &egrave; da considerarsi &copy; dei legittimi proprietari
					</div>
				</div>		
			</div>
			<!--
			<div class="f-widget last">
				<div class="widget">		
					<h3>I miei altri siti</h3>	
					<ul>
						<li>
							<a href="#">Porttitor Lectus Tincidunt Elementum Nascetur Montes</a>
						</li>
					</ul>
				</div>		
			</div>
			-->
			<div class="copyrights">
				<div class="row" id="copyright-note">
				<span>&copy; 2012 Oscar Riva</span> 
				</div>
				<div class="top"><a href="#">Back to Top</a></div>
			</div>
		</div><!--.footer-widgets-->
	</div><!--.container-->
</footer><!--footer-->